title: John Doe # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  High School Sophomore
  <br><br>
  <a href="https://www.linkedin.com/in/krishiv-piduri//">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3MZ9W9NK9M # your Google Analytics tracking ID here
